services:
    db:
        image: pgvector/pgvector:pg16
        container_name: help_db
        ports:
            - "5432:5432"
        environment: # <-- Corrigido aqui
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - postgres_data:/var/lib/postgresql/data

    app:
        build: .
        container_name: rag_help
        ports:
            - "8000:8000" # <-- Adicionado para você conseguir acessar a API do seu navegador
        volumes:
            - "./app:/app"
        environment: # <-- Corrigido aqui
            - DB_HOST=db
            - DB_PORT=5432
            - DB_USER=${POSTGRES_USER}
            - DB_PASSWORD=${POSTGRES_PASSWORD}
            - DB_NAME=${POSTGRES_DB}
            - GEMINI_API_KEY=${GEMINI_API_KEY}
        depends_on:
            - db
# command: tail -f /dev/null <-- Substituímos isso no Dockerfile pelo comando real da API

volumes:
    postgres_data: